app/meteo/forms.py
"""Copyright (c) 2020 Jaime Sendra Berenguer & Carlos Mahiques Ballester

Pebrassos - Machine Learning Library Extensions

Author:Jaime Sendra Berenguer & Carlos Mahiques Ballester
<www.linkedin.com/in/jaisenbe>

License: MIT


FECHA DE CREACIÓN: 24/01/2019

"""

from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import (StringField, SubmitField, DateField, TextAreaField, BooleanField, SelectField, IntegerField, FloatField)
from wtforms.validators import DataRequired, Length, Optional


class StationWeatherForm(FlaskForm):
    station_id = StringField('Estación Metereológica', validators=[DataRequired(), Length(max=8)])
    municipio = StringField('Municipio', validators=[DataRequired(), Length(max=80)])
    provincia = StringField('Provincia', validators=[DataRequired(), Length(max=80)])
    altura = IntegerField('Altura', validators=[DataRequired()])
    latitud = FloatField('Latitud')
    latitud_gd = FloatField('Latitud GD', validators=[DataRequired()])
    longitud = FloatField('Longitud', validators=[Length(max=8)])
    longitud_gd = FloatField('Longitud GD', validators=[DataRequired()])

    submit = SubmitField('Guardar')

app/meteo/__init__.py
"""Copyright (c) 2020 Jaime Sendra Berenguer & Carlos Mahiques Ballester

Pebrassos - Machine Learning Library Extensions

Author:Jaime Sendra Berenguer & Carlos Mahiques Ballester  
<www.linkedin.com/in/jaisenbe>

License: MIT


FECHA DE CREACIÓN: 24/05/2019

"""

from flask import Blueprint

meteo_bp = Blueprint('meteo', __name__, template_folder='templates')

from . import routes
from . import api_meteo

app/meteo/routes.py
"""Copyright (c) 2020 Jaime Sendra Berenguer & Carlos Mahiques Ballester

Pebrassos - Machine Learning Library Extensions

Author:Jaime Sendra Berenguer & Carlos Mahiques Ballester
<www.linkedin.com/in/jaisenbe>

License: MIT


FECHA DE CREACIÓN: 24/05/2019

"""

import logging
import os
import pandas as pd

from flask import render_template, redirect, url_for, request, abort, current_app
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename

from app.auth.decorators import admin_required
from app.auth.models import User
from app.models import WeatherStation
from . import meteo_bp
from .forms import StationWeatherForm

logger = logging.getLogger(__name__)


@meteo_bp.route("/meteo/")
@login_required
def index():
    return render_template("meteo/index.html")


@meteo_bp.route("/meteo/stations/")
@login_required
def list_weather_stations():
    page = int(request.args.get('page', 1))
    per_page = current_app.config['ITEMS_PER_PAGE']
    meteo_pagination = WeatherStation.all_paginated(page, per_page)
    logger.info(meteo_pagination)
    logger.info(page)
    logger.info(per_page)
    return render_template("meteo/weatherstations.html", meteo_pagination=meteo_pagination)


@meteo_bp.route("/meteo/p/<string:slug>/", methods=['GET', 'POST'])
def show_meteo_station(slug):
    logger.info('Mostrando un post')
    logger.debug(f'Slug: {slug}')
    post = WeatherStation.get_by_slug(slug)
    if not post:
        logger.info(f'La estación {slug} no existe')
        abort(404)
    return render_template("meteo/weatherstations.html", post=post)


@meteo_bp.route("/meteo/station/", methods=['GET', 'POST'])
@login_required
@admin_required
def station_form():
    """Crea una nueva estación meterológica"""
    form = StationWeatherForm()
    if form.validate_on_submit():
        station_id = form.station_id.data
        municipio = form.municipio.data
        provincia = form.provincia.data
        altura = form.altura.data
        latitud = form.latitud.data
        latitud_gd = form.latitud_gd.data
        longitud = form.longitud.data
        longitud_gd = form.longitud_gd.data

        weather_station = WeatherStation(
            station_id=station_id,
            municipio=municipio,
            provincia=provincia,
            altura=altura,
            latitud=latitud,
            latitud_gd=latitud_gd,
            longitud=longitud,
            longitud_gd=longitud_gd,
            )
        weather_station.save()
        logger.info(f'Guardada la nueva estación metereológica {station_id}:{municipio}')
        return redirect(url_for('meteo.list_weather_stations'))
    return render_template("meteo/weatherstation_form.html", form=form)


@meteo_bp.route("/meteo/station/getauto", methods=['GET', 'POST'])
@login_required
@admin_required
def station_form_auto():
    """Crea ula estaciones meterológicas automaticamente"""
    data = pd.read_csv("data/ListadoEStaciones_CSV_v04.csv", sep=";")

    stations = WeatherStation()
    stations_ids = [r.station_id for r in stations.query.distinct()]

    for i, row in data.iterrows():
        if row["ID"] in stations_ids:
            logger.info(f'{row["ID"]}:{row["MUNICIPIO"]} ya existe en la DB')
        else:
            weather_station = WeatherStation(
                station_id=row["ID"],
                municipio=row["MUNICIPIO"],
                provincia=row["PROVINCIA"],
                altura=row["ALTURA"],
                latitud=row["LATITUD"],
                latitud_gd=row["LATITUD GD"],
                longitud=row["LONGITUD"],
                longitud_gd=row["LONGITUD GD"],
                )
            weather_station.save()
            logger.info(f'Guardada la nueva estación metereológica {row["ID"]}:{row["MUNICIPIO"]}')

    return redirect(url_for('meteo.list_weather_stations'))


@meteo_bp.route("/meteo/station/<string:station_id>/", methods=['GET', 'POST'])
@login_required
@admin_required
def update_station_form(station_id):
    """Actualiza una estación existente"""
    station = WeatherStation.get_by_station(station_id)
    if station is None:
        logger.info(f'La estación {station_id} no existe')
        abort(404)
    # Crea un formulario inicializando los campos con
    # los valores del post.
    form = StationWeatherForm(obj=station)
    if form.validate_on_submit():
        # Actualiza los campos del post existente
        station.station_id = form.station_id.data
        station.municipio = form.municipio.data
        station.provincia = form.provincia.data
        station.altura = form.altura.data
        station.latitud = form.latitud.data
        station.latitud_gd = form.latitud_gd.data
        station.longitud = form.longitud.data
        station.longitud_gd = form.longitud_gd.data

        station.save()
        logger.info(f'Guardanda la estación metereológica {station_id}:{station.municipio}')
        return redirect(url_for('meteo.list_weather_stations'))
    return render_template("meteo/weatherstation_form.html", form=form, station=station)


@meteo_bp.route("/meteo/stations/delete/<string:station_id>/", methods=['POST', ])
@login_required
@admin_required
def delete_station(station_id):
    logger.info(f'Se va a eliminar la estación metereológica {station_id}')
    station = WeatherStation.get_by_station(station_id)
    if station is None:
        logger.info(f'La estación metereológica {station_id} no existe')
        abort(404)
    station.delete()
    logger.info(f'L aestación meterológica {station_id} ha sido eliminada')
    return redirect(url_for('meteo.list_weather_stations'))

app/meteo/templates/meteo/index.html
{% extends "base_template.html" %}

{% block title %}
    Pebrassos | Admin
{% endblock %}

{% block content %}
    <ul>
        <li><a href="{{ url_for('meteo.list_weather_stations') }}">Estaciones meteorológicas</a></li>
    </ul>
{% endblock %}

app/meteo/templates/meteo/weatherstation.html
{% extends "base_template.html" %}

{% block title %}
        {{station_id}}: {{data["Location_name"]}}
{% endblock %}

{% block content %}
    <li>
        <a href="{{ url_for('meteo.update_station_form', station_id=station_id) }}">Modificar estación metereológica</a>
    </li>
    <li>
        <a href="{{ url_for('meteo.database_hist_station', station_id=station_id) }}">Histórico estación metereológica</a>
    </li>
    <h3> Datos meteorológicos actuales</h3>
    <ul>
    {% for key in data %}
        <li>
            <a>{{ key }} : {{ data[key] }}</a>
        </li>
    {% endfor %}
    </ul>

{% endblock %}

app/meteo/templates/meteo/weatherstation_form.html
{% extends "base_template.html" %}

{% block title %}
    {% if form.station_id.data %}
        {{ form.station_id.data }}
    {% else %}
        Nueva estación metereológica
    {% endif %}
{% endblock %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data" novalidate>
        {{ form.hidden_tag() }}
        <div>
            {{ form.station_id.label }}
            {{ form.station_id(size=8) }}<br>
            {% for error in form.station_id.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </div>
        <div>
            {{ form.municipio.label }}
            {{ form.municipio(size=80) }}<br>
            {% for error in form.municipio.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </div>
        <div>
            {{ form.provincia.label }}
            {{ form.provincia(size=80) }}<br>
            {% for error in form.provincia.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </div>
        <div>
            {{ form.altura.label }}
            {{ form.altura}}<br>
            {% for error in form.altura.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </div>
        <div>
            {{ form.latitud_gd.label }}
            {{ form.latitud_gd}}<br>
            {% for error in form.latitud_gd.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </div>
        <div>
            {{ form.longitud_gd.label }}
            {{ form.longitud_gd}}<br>
            {% for error in form.longitud_gd.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </div>
        <div>
            {{ form.submit() }}
        </div>
    </form>
    {% if station %}
    <form action="{{ url_for('meteo.delete_station', station_id=station.station_id) }}" method="post" novalidate>
        <input type="submit" value="Eliminar" />
    </form>
    {% endif %}
{% endblock %}

app/meteo/templates/meteo/weatherstation_hist.html
{% extends "base_template.html" %}

{% block title %}
        {{station_id}}
{% endblock %}

{% block content %}

    <h3> Datos meteorológicos actuales</h3>

    <ul>
    {{ table }}
    </ul>

{% endblock %}

app/meteo/templates/meteo/weatherstations.html
{% extends "base_template.html" %}

{% block title %}
    Estaciones meteorológicas
{% endblock %}

{% block content %}
    <div>
        <a href="{{ url_for('meteo.station_form') }}">Añadir estación metereológica</a>
    </div>
    <h3>Listado de estaciones meteorológicas</h3>

    <ul>
    {% for meteo in meteo_pagination.items %}
        <li>
            <a href="{{ url_for('meteo.database_station', station_id=meteo.station_id) }}">
                {{ meteo.station_id }}: {{ meteo.municipio }} - {{ meteo.provincia }}
            </a>
        </li>
    {% else %}
        <li>No hay entradas</li>
    {% endfor %}
    </ul>

    <div class=pagination>
    {%- for page in meteo_pagination.iter_pages() %}
        {% if page %}
            {% if page != meteo_pagination.page %}
                <a href="{{ url_for('meteo.list_weather_stations', page=page) }}">{{ page }}</a>
            {% else %}
                <strong>{{ page }}</strong>
            {% endif %}
        {% else %}
            <span class=ellipsis>…</span>
        {% endif %}
    {%- endfor %}
    </div>
{% endblock %}